const weapons = [
  { name: "r-301", type: "Assault Rifle", ammo: "Light Rounds", img: "assets/img/weapons/r-301.png" },
  { name: "flatine", type: "Assault Rifle", ammo: "Heavy Rounds", img: "assets/img/weapons/flatine.png" },
  { name: "hemlok", type: "Assault Rifle", ammo: "Heavy Rounds", img: "assets/img/weapons/hemlok.png" },
  { name: "havoc", type: "Assault Rifle", ammo: "Energy Ammo", img: "assets/img/weapons/havoc.png" },
  { name: "nemisis", type: "Assault Rifle", ammo: "Energy Ammo", img: "assets/img/weapons/nemisis.png" },
  { name: "alternator", type: "SMG", ammo: "Light Rounds", img: "assets/img/weapons/alternator.png" },
  { name: "prowler", type: "SMG", ammo: "Heavy Rounds", img: "assets/img/weapons/prowler.png" },
  { name: "r-99", type: "SMG", ammo: "Light Rounds", img: "assets/img/weapons/r-99.png" },
  { name: "volt", type: "SMG", ammo: "Energy Ammo", img: "assets/img/weapons/volt.png" },
  { name: "c.a.r._smg", type: "SMG", ammo: "Light/Heavy Rounds", img: "assets/img/weapons/c.a.r._smg.png" },
  { name: "spitfire", type: "LMG", ammo: "Heavy Rounds", img: "assets/img/weapons/spitfire.png" },
  { name: "devotion", type: "LMG", ammo: "Energy Ammo", img: "assets/img/weapons/devotion.png" },
  { name: "l-star", type: "LMG", ammo: "Energy Ammo", img: "assets/img/weapons/l-star.png" },
  { name: "rampage", type: "LMG", ammo: "Heavy Rounds", img: "assets/img/weapons/rampage.png" },
  { name: "eva-8", type: "Shotgun", ammo: "Shotgun Shells", img: "assets/img/weapons/eva-8.png" },
  { name: "mastiff", type: "Shotgun", ammo: "Shotgun Shells", img: "assets/img/weapons/mastiff.png" },
  { name: "mozambique", type: "Shotgun", ammo: "Shotgun Shells", img: "assets/img/weapons/mozambique.png" },
  { name: "charge_rifle", type: "Sniper Rifle", ammo: "Sniper Ammo", img: "assets/img/weapons/charge_rifle.png" },
  { name: "sentinel", type: "Sniper Rifle", ammo: "Sniper Ammo", img: "assets/img/weapons/sentinel.png" },
  { name: "logbow", type: "Sniper Rifle", ammo: "Sniper Ammo", img: "assets/img/weapons/logbow.png" },
  { name: "g7_scout", type: "Marksman", ammo: "Light Rounds", img: "assets/img/weapons/g7_scout.png" },
  { name: "30-30_repeater", type: "Marksman", ammo: "Heavy Rounds", img: "assets/img/weapons/30-30_repeater.png" },
  { name: "bocek", type: "Marksman", ammo: "Arrows", img: "assets/img/weapons/bocek.png" },
  { name: "p2020", type: "Pistol", ammo: "Light Rounds", img: "assets/img/weapons/p2020.png" },
  { name: "re-45", type: "Pistol", ammo: "Light Rounds", img: "assets/img/weapons/re-45.png" },
  { name: "wingman", type: "Pistol", ammo: "Sniper Ammo", img: "assets/img/weapons/wingman.png" },
];

const legends = [
  { name: "Alter", img: "assets/img/legends/alter.jpg" },
  { name: "Ash", img: "assets/img/legends/ash.jpg" },
  { name: "Ballistic", img: "assets/img/legends/ballistic.jpg" },
  { name: "Bangalore", img: "assets/img/legends/bangalore.jpg" },
  { name: "Bloodhound", img: "assets/img/legends/bloodhound.jpg" },
  { name: "Catalyst", img: "assets/img/legends/catalyst.jpg" },
  { name: "Caustic", img: "assets/img/legends/caustic.jpg" },
  { name: "Conduit", img: "assets/img/legends/conduit.jpg" },
  { name: "Crypto", img: "assets/img/legends/crypto.jpg" },
  { name: "Fuse", img: "assets/img/legends/fuse.jpg" },
  { name: "Gibraltar", img: "assets/img/legends/gibraltar.jpg" },
  { name: "Horizon", img: "assets/img/legends/horizon.jpg" },
  { name: "Lifeline", img: "assets/img/legends/lifeline.jpg" },
  { name: "Loba", img: "assets/img/legends/loba.jpg" },
  { name: "Mad Maggie", img: "assets/img/legends/mad_maggie.jpg" },
  { name: "Mirage", img: "assets/img/legends/mirage.jpg" },
  { name: "Newcastle", img: "assets/img/legends/newcastle.jpg" },
  { name: "Octane", img: "assets/img/legends/octane.jpg" },
  { name: "Pathfinder", img: "assets/img/legends/pathfinder.jpg" },
  { name: "Rampart", img: "assets/img/legends/rampart.jpg" },
  { name: "Revenant", img: "assets/img/legends/revenant.jpg" },
  { name: "Seer", img: "assets/img/legends/seer.jpg" },
  { name: "Sparrow", img: "assets/img/legends/sparrow.jpg" },
  { name: "Valkyrie", img: "assets/img/legends/valkyrie.jpg" },
  { name: "Vantage", img: "assets/img/legends/vantage.jpg" },
  { name: "Wattson", img: "assets/img/legends/wattson.jpg" },
  { name: "Wraith", img: "assets/img/legends/wraith.jpg" },
];
