const weappons = [
  { name: "R-301 Carbine", type: "Assault Rifle", ammo: "Light Rounds" },
  { name: "VK-47 Flatline", type: "Assault Rifle", ammo: "Heavy Rounds" },
  { name: "Hemlok Burst AR", type: "Assault Rifle", ammo: "Heavy Rounds" },
  { name: "Havoc Rifle", type: "Assault Rifle", ammo: "Energy Ammo" },
  { name: "Nemesis Burst AR", type: "Assault Rifle", ammo: "Energy Ammo" },
  { name: "Alternator SMG", type: "SMG", ammo: "Light Rounds" },
  { name: "Prowler Burst PDW", type: "SMG", ammo: "Heavy Rounds" },
  { name: "R-99 SMG", type: "SMG", ammo: "Light Rounds" },
  { name: "Volt SMG", type: "SMG", ammo: "Energy Ammo" },
  { name: "C.A.R. SMG", type: "SMG", ammo: "Light/Heavy Rounds" },
  { name: "M600 Spitfire", type: "LMG", ammo: "Heavy Rounds" },
  { name: "Devotion LMG", type: "LMG", ammo: "Energy Ammo" },
  { name: "L-STAR EMG", type: "LMG", ammo: "Energy Ammo" },
  { name: "Rampage LMG", type: "LMG", ammo: "Heavy Rounds" },
  { name: "EVA-8 Auto", type: "Shotgun", ammo: "Shotgun Shells" },
  { name: "Peacekeeper", type: "Shotgun", ammo: "Shotgun Shells" },
  { name: "Mastiff Shotgun", type: "Shotgun", ammo: "Shotgun Shells" },
  { name: "Mozambique Shotgun", type: "Shotgun", ammo: "Shotgun Shells" },
  { name: "Longbow DMR", type: "Sniper Rifle", ammo: "Sniper Ammo" },
  { name: "Charge Rifle", type: "Sniper Rifle", ammo: "Sniper Ammo" },
  { name: "Sentinel", type: "Sniper Rifle", ammo: "Sniper Ammo" },
  { name: "Kraber .50-Cal Sniper", type: "Sniper Rifle", ammo: "Special" },
  { name: "G7 Scout", type: "Marksman", ammo: "Light Rounds" },
  { name: "Triple Take", type: "Marksman", ammo: "Energy Ammo" },
  { name: "30-30 Repeater", type: "Marksman", ammo: "Heavy Rounds" },
  { name: "Bocek Compound Bow", type: "Marksman", ammo: "Arrows" },
  { name: "P2020", type: "Pistol", ammo: "Light Rounds" },
  { name: "RE-45 Auto", type: "Pistol", ammo: "Light Rounds" },
  { name: "Wingman", type: "Pistol", ammo: "Sniper Ammo" },
];

const legends = [
  { name: "Alter", img: "assets/img/legends/alter.jpg" },
  { name: "Ash", img: "assets/img/legends/ash.jpg" },
  { name: "Ballistic", img: "assets/img/legends/ballistic.jpg" },
  { name: "Bangalore", img: "assets/img/legends/bangalore.jpg" },
  { name: "Bloodhound", img: "assets/img/legends/bloodhound.jpg" },
  { name: "Catalyst", img: "assets/img/legends/catalyst.jpg" },
  { name: "Caustic", img: "assets/img/legends/caustic.jpg" },
  { name: "Conduit", img: "assets/img/legends/conduit.jpg" },
  { name: "Crypto", img: "assets/img/legends/crypto.jpg" },
  { name: "Fuse", img: "assets/img/legends/fuse.jpg" },
  { name: "Gibraltar", img: "assets/img/legends/gibraltar.jpg" },
  { name: "Horizon", img: "assets/img/legends/horizon.jpg" },
  { name: "Lifeline", img: "assets/img/legends/lifeline.jpg" },
  { name: "Loba", img: "assets/img/legends/loba.jpg" },
  { name: "Mad Maggie", img: "assets/img/legends/mad_maggie.jpg" },
  { name: "Mirage", img: "assets/img/legends/mirage.jpg" },
  { name: "Newcastle", img: "assets/img/legends/newcastle.jpg" },
  { name: "Octane", img: "assets/img/legends/octane.jpg" },
  { name: "Pathfinder", img: "assets/img/legends/pathfinder.jpg" },
  { name: "Rampart", img: "assets/img/legends/rampart.jpg" },
  { name: "Revenant", img: "assets/img/legends/revenant.jpg" },
  { name: "Seer", img: "assets/img/legends/seer.jpg" },
  { name: "Sparrow", img: "assets/img/legends/sparrow.jpg" },
  { name: "Valkyrie", img: "assets/img/legends/valkyrie.jpg" },
  { name: "Vantage", img: "assets/img/legends/vantage.jpg" },
  { name: "Wattson", img: "assets/img/legends/wattson.jpg" },
  { name: "Wraith", img: "assets/img/legends/wraith.jpg" },
];
